//ajuda de Henrique
import java.util.Random;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author erik.martins
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a14 = new javax.swing.JButton();
        a11 = new javax.swing.JButton();
        a12 = new javax.swing.JButton();
        a13 = new javax.swing.JButton();
        a41 = new javax.swing.JButton();
        a32 = new javax.swing.JButton();
        a33 = new javax.swing.JButton();
        a44 = new javax.swing.JButton();
        a34 = new javax.swing.JButton();
        a31 = new javax.swing.JButton();
        a21 = new javax.swing.JButton();
        a22 = new javax.swing.JButton();
        a23 = new javax.swing.JButton();
        a24 = new javax.swing.JButton();
        a42 = new javax.swing.JButton();
        a43 = new javax.swing.JButton();
        txtmov = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        con1 = new javax.swing.JButton();
        cof3 = new javax.swing.JButton();
        cof2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setBounds(new java.awt.Rectangle(1, 1, 1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a14.setText("4");
        a14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a14ActionPerformed(evt);
            }
        });
        getContentPane().add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 90, 80));

        a11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a11.setText("1");
        a11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a11ActionPerformed(evt);
            }
        });
        getContentPane().add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 80));

        a12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a12.setText("2");
        a12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a12ActionPerformed(evt);
            }
        });
        getContentPane().add(a12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 80));

        a13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a13.setText("3");
        a13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a13ActionPerformed(evt);
            }
        });
        getContentPane().add(a13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 80));

        a41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a41.setText("13");
        a41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a41ActionPerformed(evt);
            }
        });
        getContentPane().add(a41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 90, 80));

        a32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a32.setText("10");
        a32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a32ActionPerformed(evt);
            }
        });
        getContentPane().add(a32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 90, 80));

        a33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a33.setText("11");
        a33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a33ActionPerformed(evt);
            }
        });
        getContentPane().add(a33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 90, 80));

        a44.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a44ActionPerformed(evt);
            }
        });
        getContentPane().add(a44, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 90, 80));

        a34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a34.setText("12");
        a34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a34ActionPerformed(evt);
            }
        });
        getContentPane().add(a34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, 80));

        a31.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a31.setText("9");
        a31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a31ActionPerformed(evt);
            }
        });
        getContentPane().add(a31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 80));

        a21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a21.setText("5");
        a21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a21ActionPerformed(evt);
            }
        });
        getContentPane().add(a21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 80));

        a22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a22.setText("6");
        a22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a22ActionPerformed(evt);
            }
        });
        getContentPane().add(a22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, 80));

        a23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a23.setText("7");
        a23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a23ActionPerformed(evt);
            }
        });
        getContentPane().add(a23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, 80));

        a24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a24.setText("8");
        a24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a24ActionPerformed(evt);
            }
        });
        getContentPane().add(a24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 90, 80));

        a42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a42.setText("14");
        a42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a42ActionPerformed(evt);
            }
        });
        getContentPane().add(a42, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 90, 80));

        a43.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        a43.setText("15");
        a43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a43ActionPerformed(evt);
            }
        });
        getContentPane().add(a43, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 90, 80));

        txtmov.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtmov, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 270, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Embaralhar (fase De Teste)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 220, 50));

        con1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        con1.setText("Configuração 1");
        con1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                con1ActionPerformed(evt);
            }
        });
        getContentPane().add(con1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 170, 40));

        cof3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cof3.setText("Configuração 3");
        cof3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cof3ActionPerformed(evt);
            }
        });
        getContentPane().add(cof3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 170, 40));

        cof2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cof2.setText("Configuração 2");
        cof2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cof2ActionPerformed(evt);
            }
        });
        getContentPane().add(cof2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int c;
    
    
    
    void Troca(JButton but1, JButton but2){
        String num = but2.getText();
        if(num==""){
            but2.setText(but1.getText()); 
            but1.setText("");
            c++;
            txtmov.setText("Número De Movimentos: " + Integer.toString(c));
            
            if(a11.getText()=="1" && 
               a12.getText()=="2" &&
               a13.getText()=="3" &&
               a14.getText()=="4" &&
               a21.getText()=="5" && 
               a22.getText()=="6" &&
               a23.getText()=="7" &&
               a24.getText()=="8" &&
               a31.getText()=="9" && 
               a32.getText()=="10" &&
               a33.getText()=="11" &&
               a34.getText()=="12" &&
               a41.getText()=="13" && 
               a42.getText()=="14" &&
               a43.getText()=="15" &&
               c != 0){
                
                txtmov.setText("VOCE GANHOU!!!");
                c = 0;    
            }
        }
       
    }
    private void a11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a11ActionPerformed
        // TODO add your handling code here:
        Troca(a11,a12);
        Troca(a11,a21);   
    }//GEN-LAST:event_a11ActionPerformed

    private void a12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a12ActionPerformed
        // TODO add your handling code here:
        Troca(a12,a11);
        Troca(a12,a22);
        Troca(a12,a13);
    }//GEN-LAST:event_a12ActionPerformed

    private void a13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a13ActionPerformed
        // TODO add your handling code here:
        Troca(a13,a12);
        Troca(a13,a14);
        Troca(a13,a23);
    }//GEN-LAST:event_a13ActionPerformed

    private void a14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a14ActionPerformed
        // TODO add your handling code here:
        Troca(a14,a13);
        Troca(a14,a24);
    }//GEN-LAST:event_a14ActionPerformed

    private void a21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a21ActionPerformed
        // TODO add your handling code here:
        Troca(a21,a11);
        Troca(a21,a22);
        Troca(a21,a31);
    }//GEN-LAST:event_a21ActionPerformed

    private void a22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a22ActionPerformed
        // TODO add your handling code here:
        Troca(a22,a12);
        Troca(a22,a21);
        Troca(a22,a23);
        Troca(a22,a32);
    }//GEN-LAST:event_a22ActionPerformed

    private void a23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a23ActionPerformed
        // TODO add your handling code here:
        Troca(a23,a13);
        Troca(a23,a22);
        Troca(a23,a24);
        Troca(a23,a33);
    }//GEN-LAST:event_a23ActionPerformed

    private void a24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a24ActionPerformed
        // TODO add your handling code here:
        Troca(a24,a14);
        Troca(a24,a23);
        Troca(a24,a34);
    }//GEN-LAST:event_a24ActionPerformed

    private void a31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a31ActionPerformed
        // TODO add your handling code here:
        Troca(a31,a21);
        Troca(a31,a32);
        Troca(a31,a41);
    }//GEN-LAST:event_a31ActionPerformed

    private void a32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a32ActionPerformed
        // TODO add your handling code here:
        Troca(a32,a31);
        Troca(a32,a33);
        Troca(a32,a42);
        Troca(a32,a22);
    }//GEN-LAST:event_a32ActionPerformed

    private void a33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a33ActionPerformed
        // TODO add your handling code here:
        Troca(a33,a32);
        Troca(a33,a34);
        Troca(a33,a43);
        Troca(a33,a23);
    }//GEN-LAST:event_a33ActionPerformed

    private void a34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a34ActionPerformed
        // TODO add your handling code here:
        Troca(a34,a33);
        Troca(a34,a24);
        Troca(a34,a44);
    }//GEN-LAST:event_a34ActionPerformed

    private void a41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a41ActionPerformed
        // TODO add your handling code here:
        Troca(a41,a31);
        Troca(a41,a42);
    }//GEN-LAST:event_a41ActionPerformed

    private void a42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a42ActionPerformed
        // TODO add your handling code here:
        Troca(a42,a41);
        Troca(a42,a43);
        Troca(a42,a32);
    }//GEN-LAST:event_a42ActionPerformed

    private void a43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a43ActionPerformed
        // TODO add your handling code here:
        Troca(a43,a42);
        Troca(a43,a44);
        Troca(a43,a33);
    }//GEN-LAST:event_a43ActionPerformed

    private void a44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a44ActionPerformed
        // TODO add your handling code here:
        Troca(a44,a34);
        Troca(a44,a43);
    }//GEN-LAST:event_a44ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int vet[]= new int[16];
        Random embaralhar = new Random();
        for(int i=0; i< vet.length; i++){
            vet[i]= embaralhar.nextInt(15)+1;
            
            a11.setText(Integer.toString(vet[1]));
            a12.setText(Integer.toString(vet[2]));
            a13.setText(Integer.toString(vet[3]));
            a14.setText(Integer.toString(vet[4]));
            a21.setText(Integer.toString(vet[5]));
            a22.setText(Integer.toString(vet[6]));
            a23.setText(Integer.toString(vet[7]));
            a24.setText(Integer.toString(vet[8]));
            a31.setText(Integer.toString(vet[9]));
            a32.setText(Integer.toString(vet[10]));
            a33.setText(Integer.toString(vet[11]));
            a34.setText(Integer.toString(vet[12]));
            a41.setText(Integer.toString(vet[13]));
            a42.setText(Integer.toString(vet[14]));
            a43.setText(Integer.toString(vet[15]));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void con1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_con1ActionPerformed
        // TODO add your handling code here:
        int vet[] = {6,2,4,15,5,14,3,8,1,11,9,12,10,7,13};
        
        a11.setText(Integer.toString(vet[0]));
        a12.setText(Integer.toString(vet[1]));
        a13.setText(Integer.toString(vet[2]));
        a14.setText(Integer.toString(vet[3]));
        a21.setText(Integer.toString(vet[4]));
        a22.setText(Integer.toString(vet[5]));
        a23.setText(Integer.toString(vet[6]));
        a24.setText(Integer.toString(vet[7]));
        a31.setText(Integer.toString(vet[8]));
        a32.setText(Integer.toString(vet[9]));
        a33.setText(Integer.toString(vet[10]));
        a34.setText(Integer.toString(vet[11]));
        a41.setText(Integer.toString(vet[12]));
        a42.setText(Integer.toString(vet[13]));
        a43.setText(Integer.toString(vet[14]));
    }//GEN-LAST:event_con1ActionPerformed

    private void cof3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cof3ActionPerformed
        // TODO add your handling code here:
        int vet[] = {4,7,5,10,15,3,12,2,6,14,13,9,8,11,1};
        
        a11.setText(Integer.toString(vet[0]));
        a12.setText(Integer.toString(vet[1]));
        a13.setText(Integer.toString(vet[2]));
        a14.setText(Integer.toString(vet[3]));
        a21.setText(Integer.toString(vet[4]));
        a22.setText(Integer.toString(vet[5]));
        a23.setText(Integer.toString(vet[6]));
        a24.setText(Integer.toString(vet[7]));
        a31.setText(Integer.toString(vet[8]));
        a32.setText(Integer.toString(vet[9]));
        a33.setText(Integer.toString(vet[10]));
        a34.setText(Integer.toString(vet[11]));
        a41.setText(Integer.toString(vet[12]));
        a42.setText(Integer.toString(vet[13]));
        a43.setText(Integer.toString(vet[14]));
    }//GEN-LAST:event_cof3ActionPerformed

    private void cof2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cof2ActionPerformed
        // TODO add your handling code here:
        int vet[] = {5,7,4,8,3,2,1,14,11,15,6,12,13,10,9};
        
        a11.setText(Integer.toString(vet[0]));
        a12.setText(Integer.toString(vet[1]));
        a13.setText(Integer.toString(vet[2]));
        a14.setText(Integer.toString(vet[3]));
        a21.setText(Integer.toString(vet[4]));
        a22.setText(Integer.toString(vet[5]));
        a23.setText(Integer.toString(vet[6]));
        a24.setText(Integer.toString(vet[7]));
        a31.setText(Integer.toString(vet[8]));
        a32.setText(Integer.toString(vet[9]));
        a33.setText(Integer.toString(vet[10]));
        a34.setText(Integer.toString(vet[11]));
        a41.setText(Integer.toString(vet[12]));
        a42.setText(Integer.toString(vet[13]));
        a43.setText(Integer.toString(vet[14]));
    }//GEN-LAST:event_cof2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a11;
    private javax.swing.JButton a12;
    private javax.swing.JButton a13;
    private javax.swing.JButton a14;
    private javax.swing.JButton a21;
    private javax.swing.JButton a22;
    private javax.swing.JButton a23;
    private javax.swing.JButton a24;
    private javax.swing.JButton a31;
    private javax.swing.JButton a32;
    private javax.swing.JButton a33;
    private javax.swing.JButton a34;
    private javax.swing.JButton a41;
    private javax.swing.JButton a42;
    private javax.swing.JButton a43;
    private javax.swing.JButton a44;
    private javax.swing.JButton cof2;
    private javax.swing.JButton cof3;
    private javax.swing.JButton con1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel txtmov;
    // End of variables declaration//GEN-END:variables
}
